MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    NUM_CLASSES: 5
  # PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
DATASETS:
  TRAIN: ("images_with_night",)
  TEST: ("coco_traffic_unresized_test",)
SOLVER:
  IMS_PER_BATCH: 20
  BASE_LR: 0.002  # Note that RetinaNet uses a different default learning rate
  STEPS: (600, 800)
  MAX_ITER: 900
  WARMUP_ITERS: 300
INPUT:
  #MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  #MIN_SIZE_TRAIN_FIX: (470,)
  MIN_SIZE_TRAIN: (470,)
  MIN_SIZE_TEST: 470
  MAX_SIZE_TEST: 800
DATALOADER:
  NUM_WORKERS: 4

  
