_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "/home/ghr/traffic_sign/config_resnet18/resnet18.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/fcos/R18"
